### ISSUE TITLE
Runtime error when changing proofing language

### ISSUE THREAD

**Issue by fvdnieuwboer** [iappyx/Instrumenta#10] opened 2021-05-18 21:05 UTC
**Describe the bug**
Changing the proofing language of all slides to any langauge results in an runtime error (see screenshot). I am using v0.81 of the toolbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/3865081/118722999-1f1d8700-b82d-11eb-95a1-fe64d00f451b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise
 - O365 PPT

**Additional context**

**Comment by iappyx** [comment] 2021-05-18 21:41
Thanks for flagging this. Cannot reproduce it yet, will look into it. Might have something to do with special shapes or objects you have one of the slides. Does it also occur with a new (empty) presentation?

**Comment by iappyx** [comment] 2021-05-18 22:21
Think I found it. Should be fixed in the latest version (0.83). Let me know if it works for you.

**Closed by iappyx** 2021-05-18 22:21 UTC
Labels: bug
